import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import profilePic from "../../public/images/profile/profile-5.png"
import AnimatedText from '@/components/AnimatedText'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        
      </Head>
      <main className='flex items-center text-dark w-full min-h-screen'>
          
          <Layout className='pt-0'>

            <div className = "flex items-center justify-between w-full">
              <div className='w-1/2'>
                <Image src={profilePic} alt="Adinath" className='w-full h-auto pb-5 pr-10'/>
              </div>
              <div className='w-1/2 flex flex-col items-center self-center'>
                
                <AnimatedText text = "Beyond code,           I solve problems." className = '!text-6xl !text-left '/>

                  <p>
                  With C/C++, Python, React.js, and SQL in my arsenal, I'm more than just a coder. Dive in my Next.js portfolio, where logic and data structures dance with object-oriented design to create beautiful, functional solutions. Let's collaborate and turn challenges into opportunities.
                  </p>
                
              </div>
            </div>

          </Layout>

      </main>
    </>
  )
}
